spring:
  application:
    name: DoctorAppBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/doctor
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    org.hibernate.validator.internal.engine.constraintvalidation: DEBUG
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
